# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9668d02bccafae4261001ac69f90b4fc6608ba1e65fa52f1c436d8fd086db63c16ad921c52420fcaca764a3af1f198dc1d5156b3f8c5596ede08dd5b2bffdcca
  mifiel_app_id: <%= ENV['MIFIEL_APP_ID']ENV['MIFIEL_APP_ID'] %>
  mifiel_app_secret: <%= ENV['MIFIEL_APP_SECRET'] %>
  mifiel_host: 'https://sandbox.mifiel.com/api/v1'

test:
  secret_key_base: 61a24ed29913c8abab6429285735cb44069554ef0337d86cfcf0e278be935a93feb476e03071c6a642b00b28671f005d93841b9e83559048916b29fb3ab60156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mifiel_app_id: <%= ENV['MIFIEL_APP_ID']ENV['MIFIEL_APP_ID'] %>
  mifiel_app_secret: <%= ENV['MIFIEL_APP_SECRET'] %>
  mifiel_host: 'https://sandbox.mifiel.com/api/v1'
